### ISSUE TITLE
No prompt to resize images on Thunderbird Beta 

### ISSUE THREAD

**Issue by m0rgano** [memeller/shrunked#31] opened 2024-06-23 16:01 UTC
**Describe the bug**
There is no prompt to resize the image when it is inserted or attached to the message.

**To Reproduce**
Insert or attach an image to a new message.

**Expected behavior**
A prompt should appear at the bottom of the screen offering to resize the image.

**Screenshots**

**Desktop (please complete the following information):**
1. Os = Windows 10
2. Thunderbird version = 128.0b3 
3. Extension version = 5.8.1
4. Image details - format, size, Any JPEG, PNG etc.
5. Extension settings = default settings
6. If you are having issues with manual resizing: 
- Is the notification displayed when image is attached - No
- Is the notification displayed when image is inserted inline - No
- Is there an option to resize the image when right clicking on attached / inline images - No
7. Did this feature work in previous versions - Yes (not sure if on any 128.x.x versions though)

**Additional context**
Add any other context about the problem here. Please add e.g. debug log (Tools -> Developer Tools -> Error console)

**Comment by memeller** [comment] 2024-06-24 10:45
I am sorry that the extension is not working in this build. 
Since this is not the first time for a beta build - as noted in #22 
> Beta and nightly builds are not supported. Checking the release notes i see no breaking changes, so I assume this might be a beta build bug, that will be fixed before the stable release. If the problem is still present in the next stable build, please let me know.
Please also keep in mind that this addon uses an experimental Thunderbird feature to add resize functionality and that this feature might be removed from Thunderbird at some point in future. As with #22 I do not see any breaking changes in the release notes for this beta build.

**Comment by memeller** [comment] 2024-06-28 18:57
[shrunked_tb_beta5_change_ext_to_xpi.zip](https://github.com/user-attachments/files/16035640/shrunked_tb_beta5_change_ext_to_xpi.zip)
Ok, so I was curious what the problem was and it seems that ChromeUtils now requires different imports.
@m0rgano can you test the attached version? Just change the extension from zip to xpi first.

**Comment by m0rgano** [comment] 2024-06-28 20:51
@memeller 
Yes, your change appears to have fixed it - thanks! :-)
The new add-on shows as V 5.7.2 by the way - not sure if that was intentional?

**Comment by memeller** [comment] 2024-06-30 09:55
@m0rgano I went back to an older version first to see if the problem was with recent changes, and then made changes in that version, so 5.7.2 was correct for the attached file.
v5.8.2 is now online with v128 beta compatibility fixed and all the features of v5.8.1. 
I did a quick test and everything seems to work fine. I am closing this as complete.

**Closed by memeller** 2024-06-30 09:55 UTC

**Comment by Betterbird** [comment] 2024-07-07 10:08
Confirmed working also on version 128.0esr. Thanks to much for your work!
