### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by moreje** [memeller/shrunked#22] opened 2024-02-11 02:09 UTC
still not working with TB 123.0b4 
no skrink menu when sending email with big jpg photos

**Comment by memeller** [comment] 2024-02-11 10:46
Beta and nightly builds are not supported. Checking the [release notes](https://www.thunderbird.net/en-US/thunderbird/123.0beta/releasenotes/) i see no breaking changes, so I assume this might be a beta build bug, that will be fixed before the stable release. 
If the problem is still present in the 123 stable build, please report this bug with additional details, such as:
1. Version of the extension and OS,
2. Image details - format, size,
3. Extension settings,
4. Is the notification displayed when image is attached,
5. Is the notification displayed when image is inserted inline,
6. Is there an option to resize the image when right clicking on attached / inline images
7. If you are able to test other versions of this extension, please provide details if any of them work as expected.

**Closed by memeller** 2024-02-11 10:46 UTC
